#!/usr/bin/env bash
# Prints 1–20 with special messages on 4, 9, 17 using case
i=1
while [ $i -le 20 ]; do
  case $i in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo "$i"
      ;;
  esac
  ((i++))
done
